import json
import pickle
import random
import string
import time

from Crypto.Hash import SHA256
from Crypto.Cipher import AES

import data_structures
from data_structures import deobjectify, Group, Chat, Member, Organisation, Message, Member_Private
from user import sign_up, sign_in, chat_functionality_v2, recieve, send
from server import validate_user, manage_users, communicate
import auxiliary

count_calls = [0,0,0,0,0]
names = [{"name":"Lisle Soffe"},
{"name":"Ralina Gammons"},
{"name":"Yardley Bonhome"},
{"name":"Ninetta Klimke"},
{"name":"Aldon Ducker"},
{"name":"Myriam Lightwing"},
{"name":"Marielle Tantum"},
{"name":"Berry Batrim"},
{"name":"Letti Rozycki"},
{"name":"Trenton Letchford"},
{"name":"Daren Norgate"},
{"name":"Jerrie Dunkerly"},
{"name":"Fawnia Lovewell"},
{"name":"Kinna Delmonti"},
{"name":"Franciska Zute"},
{"name":"Regine Fawdery"},
{"name":"Eachelle Tootell"},
{"name":"Drusi Etherington"},
{"name":"Pieter Waskett"},
{"name":"Amata Canland"},
{"name":"Nolana Balogun"},
{"name":"Dayna Fehner"},
{"name":"Florry Bertolaccini"},
{"name":"Kristoffer Kivlehan"},
{"name":"Krystal Feckey"},
{"name":"Jamie Boyet"},
{"name":"Rois Patise"},
{"name":"Austen Zamboniari"},
{"name":"Dorena Jillitt"},
{"name":"Murvyn Wheeldon"},
{"name":"Marylinda Rugieri"},
{"name":"Alair Stitch"},
{"name":"Devonne Saxelby"},
{"name":"Cordie Vitte"},
{"name":"Darrelle Yarrington"},
{"name":"Anallese Penreth"},
{"name":"Sharyl Musico"},
{"name":"Eddy Chomicz"},
{"name":"Benny Lace"},
{"name":"Brier Ramage"},
{"name":"Karlis Beardsell"},
{"name":"Flem Burchall"},
{"name":"Gerri Grafham"},
{"name":"Millard Forbear"},
{"name":"Grantham Cancellor"},
{"name":"Stuart Barry"},
{"name":"Alfons Fearby"},
{"name":"Christina Waddy"},
{"name":"Zacharias Macquire"},
{"name":"Cherrita Della"},
{"name":"Emma Stockin"},
{"name":"Livvy Mantripp"},
{"name":"Bentley Nast"},
{"name":"Kristen Helm"},
{"name":"Ardene Adamini"},
{"name":"Darcie Gloster"},
{"name":"Sheree Korfmann"},
{"name":"Carlynne Buttfield"},
{"name":"Linnell Brambell"},
{"name":"Ara Reinger"},
{"name":"Carlita Venes"},
{"name":"Dyna Teggart"},
{"name":"Guy Baudon"},
{"name":"Jenica Lammenga"},
{"name":"Barbra Ireland"},
{"name":"Cord Edington"},
{"name":"Johna Denman"},
{"name":"Anastassia Gravy"},
{"name":"Rhianon Pales"},
{"name":"Sanford Tewes"},
{"name":"Nonnah Philippeaux"},
{"name":"Alexis Prigmore"},
{"name":"Georgeanna D'Andrea"},
{"name":"Lulu Warrillow"},
{"name":"Berti Tammadge"},
{"name":"Devland Holton"},
{"name":"Henrietta Chaves"},
{"name":"Tanny Jennick"},
{"name":"Curtice Boman"},
{"name":"Delila Hryniewicz"},
{"name":"Louie Haythornthwaite"},
{"name":"Silvan Gaskarth"},
{"name":"Belle Cowill"},
{"name":"Pepillo Worley"},
{"name":"Lindsay Stappard"},
{"name":"Jamesy Pagett"},
{"name":"Prince Letessier"},
{"name":"Guenna Maiden"},
{"name":"Barbi Drogan"},
{"name":"Lalo Shier"},
{"name":"Ranice Nealon"},
{"name":"Jan Brotherheed"},
{"name":"Dene Cogan"},
{"name":"Pauline Saul"},
{"name":"Elwira Pinckney"},
{"name":"Ursala Gendrich"},
{"name":"Rosana Sone"},
{"name":"Lazare Houtby"},
{"name":"Malcolm Atherton"},
{"name":"Maureene Kupke"},
{"name":"Babara Tramel"},
{"name":"Leandra Lazell"},
{"name":"Sigfried Daouse"},
{"name":"Mariette Pelerin"},
{"name":"Dud Chadwin"},
{"name":"Abbey Paolacci"},
{"name":"Kial Hulse"},
{"name":"Isis Paulon"},
{"name":"Ajay Cranmore"},
{"name":"Astrid Raynard"},
{"name":"Dana Borgesio"},
{"name":"Zaria Donohue"},
{"name":"Barry Jilliss"},
{"name":"Sapphira Bellay"},
{"name":"Cherlyn Caff"},
{"name":"Dicky Tuma"},
{"name":"Bridget Swannick"},
{"name":"Othella Ugoletti"},
{"name":"Ferne Calderwood"},
{"name":"Halli Canadine"},
{"name":"Marika Boullen"},
{"name":"Berky Bourthoumieux"},
{"name":"Alla Guppie"},
{"name":"Adriana Kershaw"},
{"name":"Pepito Wiltshier"},
{"name":"L;urette Burke"},
{"name":"Trey Spaule"},
{"name":"Bettine Reames"},
{"name":"Phelia Botler"},
{"name":"Vanni Rowthorn"},
{"name":"Bernarr Connell"},
{"name":"Raphaela Mahaddie"},
{"name":"Ronny Haughan"},
{"name":"Jemie Roller"},
{"name":"Eleni Amyes"},
{"name":"Caitrin Vannuccinii"},
{"name":"Vidovic Kensy"},
{"name":"Ottilie De-Ville"},
{"name":"Lilyan Clarey"},
{"name":"Agretha Burnsall"},
{"name":"Curry Uwins"},
{"name":"Jacklin Rosenschein"},
{"name":"Bernardo Scotter"},
{"name":"Yanaton Pachmann"},
{"name":"Emmalynn Prophet"},
{"name":"Whitney Eden"},
{"name":"Keen Lewendon"},
{"name":"Juliette Hamon"},
{"name":"Doyle DelaField"},
{"name":"Cirstoforo Fishpool"},
{"name":"Haley Parkisson"},
{"name":"Levi Toop"},
{"name":"Lizzie Heart"},
{"name":"Nedda Shand"},
{"name":"Rubin Arney"},
{"name":"Wendel Althorp"},
{"name":"Carmelita Hacun"},
{"name":"Tomi Deniso"},
{"name":"Leila Bruyett"},
{"name":"Rodrigo Baalham"},
{"name":"Anny Crippell"},
{"name":"Tedmund Whysall"},
{"name":"Rycca Arnaez"},
{"name":"Hildegaard Dadley"},
{"name":"Gerald McKim"},
{"name":"Buiron O'Heffernan"},
{"name":"Arney Brackpool"},
{"name":"Barney Hardi"},
{"name":"Roselin Vertigan"},
{"name":"Elwin Sandy"},
{"name":"Grantham Herrema"},
{"name":"Sabra Steffens"},
{"name":"Lucais Scatchar"},
{"name":"Suzann Birtwisle"},
{"name":"Wrennie Chessil"},
{"name":"Cristin Brithman"},
{"name":"Bren Cavet"},
{"name":"Teri Tolerton"},
{"name":"Aaron Lathwell"},
{"name":"Minta Wahner"},
{"name":"Wakefield McGeagh"},
{"name":"Myrwyn Glasson"},
{"name":"Evyn Kondratyuk"},
{"name":"Kylie Idale"},
{"name":"Whitney Leet"},
{"name":"Puff Kort"},
{"name":"Silvie Gate"},
{"name":"Denise Pagitt"},
{"name":"Kare Siddell"},
{"name":"Zacherie Cocke"},
{"name":"Riccardo Folan"},
{"name":"Jaye Heigl"},
{"name":"Gav Cannavan"},
{"name":"Eugen Ander"},
{"name":"Tripp Dodsworth"},
{"name":"Berty Primett"},
{"name":"Antonietta Coppenhall"},
{"name":"Brantley Dacks"},
{"name":"Ernaline Brittian"},
{"name":"Hollyanne Earthfield"},
{"name":"Cristionna Khotler"},
{"name":"Ethyl Wolfit"},
{"name":"Austina Chooter"},
{"name":"Leoline Gillan"},
{"name":"Caressa Lynam"},
{"name":"Noak Virr"},
{"name":"Ilyssa Benettelli"},
{"name":"Tuckie Lill"},
{"name":"Etienne McLarens"},
{"name":"Lowell Shinfield"},
{"name":"Francisco Golsthorp"},
{"name":"Earlie Patty"},
{"name":"Giovanni Foreman"},
{"name":"Fitzgerald Dewey"},
{"name":"Gaston Habbal"},
{"name":"Byrann Lowey"},
{"name":"Celka Strode"},
{"name":"Roscoe Cloney"},
{"name":"Saxe O'Hear"},
{"name":"Tania Pfeuffer"},
{"name":"Stan Abelovitz"},
{"name":"Thomasin Matteini"},
{"name":"Elsworth Brocklebank"},
{"name":"Skyler Hassan"},
{"name":"Grenville Crowder"},
{"name":"Tim Matitiaho"},
{"name":"Lorenza Baudic"},
{"name":"Ezequiel Tebbs"},
{"name":"Bret Ielden"},
{"name":"Ninnette Pettifer"},
{"name":"Wenonah Osburn"},
{"name":"Regina Crellin"},
{"name":"Lydia Macallam"},
{"name":"Darryl Brookson"},
{"name":"Millisent Fitzpayn"},
{"name":"Earle Biddwell"},
{"name":"Whitaker Gorner"},
{"name":"Danny Osselton"},
{"name":"Robby Struttman"},
{"name":"Kristal Mangan"},
{"name":"Darin Heskey"},
{"name":"Arlene Burkill"},
{"name":"Raffaello Goldston"},
{"name":"Doreen Gulberg"},
{"name":"Dannel Readman"},
{"name":"Ruthanne Baskerfield"},
{"name":"Izabel Hopkynson"},
{"name":"Derrek Whitcombe"},
{"name":"Natividad Paunsford"},
{"name":"Stesha Linklater"},
{"name":"Daphne Sindell"},
{"name":"Sadie D'Andrea"},
{"name":"Baillie Landal"},
{"name":"Giacomo Leng"},
{"name":"Tiebout Jakoviljevic"},
{"name":"Bellanca Putton"},
{"name":"Anabel Clement"},
{"name":"Reynold Dickman"},
{"name":"Nicko Georgi"},
{"name":"Axe Concannon"},
{"name":"Malvina Katzmann"},
{"name":"Patsy Tackle"},
{"name":"Bevon Kingzeth"},
{"name":"Christiana Scaife"},
{"name":"Marilin Rubury"},
{"name":"Dorian Beckworth"},
{"name":"Randolf Pedlar"},
{"name":"Jayne Sumner"},
{"name":"Deloria Josipovitz"},
{"name":"Scot Whates"},
{"name":"Erl Shama"},
{"name":"Janel Kernley"},
{"name":"Kailey McClay"},
{"name":"Curcio Lushey"},
{"name":"Englebert Tokell"},
{"name":"Cam Collingworth"},
{"name":"Rachelle Filippucci"},
{"name":"Rochell Keijser"},
{"name":"Rodolfo Litt"},
{"name":"Gilberte Brown"},
{"name":"Gabbi Goss"},
{"name":"Florinda Curness"},
{"name":"Thorsten Casaro"},
{"name":"Ollie Skates"},
{"name":"Ruttger Walton"},
{"name":"Kenny Showt"},
{"name":"Fran Ellington"},
{"name":"Dotti McSkin"},
{"name":"Skell Pleasaunce"},
{"name":"Corissa Chettle"},
{"name":"Lishe Sallings"},
{"name":"Gabe Coal"},
{"name":"Frederic Whetton"},
{"name":"Reginauld Delgardo"},
{"name":"Beniamino Pegg"},
{"name":"Jemmie Harberer"},
{"name":"Ashil Shoebridge"},
{"name":"Goddard Nias"},
{"name":"Reube Harroway"},
{"name":"Kippy Birchett"},
{"name":"Lauretta Mastrantone"},
{"name":"Dodi Alabone"},
{"name":"Paul Vayne"},
{"name":"Ellswerth Figge"},
{"name":"Warren Naden"},
{"name":"Sylvia Kreuzer"},
{"name":"Hyacinthia Cathersides"},
{"name":"Kimberly Oleszkiewicz"},
{"name":"Brana Haigh"},
{"name":"Jacquetta Kitchaside"},
{"name":"Nanice Tosh"},
{"name":"Andre Beccera"},
{"name":"Kelley Didsbury"},
{"name":"Jerrilyn Koeppke"},
{"name":"Augustus Reddel"},
{"name":"Even Tabram"},
{"name":"Esmaria Ritzman"},
{"name":"Sterne Maxstead"},
{"name":"Reginauld Kettlestringes"},
{"name":"Ive Peirone"},
{"name":"Daniel Premble"},
{"name":"Otis Chupin"},
{"name":"Cybil Dorre"},
{"name":"Terza Mila"},
{"name":"Gui Anscott"},
{"name":"Glennis Roze"},
{"name":"Ellyn Bartolommeo"},
{"name":"Annadiane Trangmar"},
{"name":"Glory Margerrison"},
{"name":"Natalee Breton"},
{"name":"Barbaraanne Newbury"},
{"name":"Flynn Mechem"},
{"name":"Latia Reihill"},
{"name":"Teodorico Tunuy"},
{"name":"Moina Albrecht"},
{"name":"Eduardo Brew"},
{"name":"Chrissie Edelman"},
{"name":"Alison Gainsbury"},
{"name":"Ailene Duckels"},
{"name":"Vally Bailles"},
{"name":"Cordie Gobel"},
{"name":"Tallia Casino"},
{"name":"Dolli Wherry"},
{"name":"Richardo Usmar"},
{"name":"Thaxter Fyndon"},
{"name":"Hank Rayman"},
{"name":"Jacquelin Ripon"},
{"name":"Art Quartermain"},
{"name":"Dorine Eles"},
{"name":"Obidiah Fryer"},
{"name":"Gratia Hansie"},
{"name":"Meg Rickardes"},
{"name":"Daphna Keelinge"},
{"name":"Elyn Leicester"},
{"name":"Evelyn Tack"},
{"name":"Olivie Hedney"},
{"name":"Judi Kehir"},
{"name":"Reagan Strothers"},
{"name":"Tymon Raspison"},
{"name":"Sherm Sewter"},
{"name":"Josh Tillman"},
{"name":"Kinna Resun"},
{"name":"Daune McCrohon"},
{"name":"Beverie Smyth"},
{"name":"Hakim Ferreira"},
{"name":"Corny Goad"},
{"name":"Rutledge de Nore"},
{"name":"Cornall Avrahamian"},
{"name":"Norene Dunseath"},
{"name":"Leeanne Heaysman"},
{"name":"Billie Treker"},
{"name":"Llewellyn Sivell"},
{"name":"Grady Lovelock"},
{"name":"Kiley Yushachkov"},
{"name":"Devondra Wickardt"},
{"name":"Woodie Allan"},
{"name":"Yule Kinsett"},
{"name":"Glori Godsal"},
{"name":"Cybil Livesley"},
{"name":"Derk Vannuccinii"},
{"name":"Mildrid Deaville"},
{"name":"Bren Upjohn"},
{"name":"Tova McManamen"},
{"name":"Dannel Grishaev"},
{"name":"Jewel Annott"},
{"name":"Jorge Edgington"},
{"name":"Brannon Bettley"},
{"name":"Collette Roback"},
{"name":"Karlene Stendell"},
{"name":"Verna Sphinxe"},
{"name":"Gregorio Inott"},
{"name":"Chilton Wyles"},
{"name":"Roma Turfs"},
{"name":"Ambrosio Scruby"},
{"name":"Rudyard Driffield"},
{"name":"Farlay Austwick"},
{"name":"Maura Davenell"},
{"name":"Bendite Whitta"},
{"name":"Jackelyn Tafani"},
{"name":"Micheline Labb"},
{"name":"Nicolina Tendahl"},
{"name":"Otho Kingswood"},
{"name":"Hobie Brewitt"},
{"name":"Welch Ericsson"},
{"name":"Broddy Wilsdon"},
{"name":"Ginni Pendlebery"},
{"name":"Berenice Kayne"},
{"name":"Ransell Kale"},
{"name":"Kara-lynn Pieters"},
{"name":"Parke Lindner"},
{"name":"Lexi Potte"},
{"name":"Samantha Breukelman"},
{"name":"Kathie Cawthorne"},
{"name":"Jacky Grancher"},
{"name":"Gwynne Huthart"},
{"name":"Marianne Gilbride"},
{"name":"Ashlie Warboys"},
{"name":"Gnni Benyan"},
{"name":"Neil Belderson"},
{"name":"Del Marcinkus"},
{"name":"Lauree Wykes"},
{"name":"Hamil Surmon"},
{"name":"Jinny Cashin"},
{"name":"Saul Jarnell"},
{"name":"Binny Shannahan"},
{"name":"Lauralee Menlow"},
{"name":"Wyn Rouzet"},
{"name":"Boony Chern"},
{"name":"Barbara-anne Duns"},
{"name":"Alexi Saunderson"},
{"name":"Christyna Nesby"},
{"name":"Morty Pedrol"},
{"name":"Claudie Langstaff"},
{"name":"Nonah Apperley"},
{"name":"Nadine MacMurray"},
{"name":"Kynthia Thaine"},
{"name":"Jacklin Gentric"},
{"name":"Christina Stiegar"},
{"name":"Sidonnie Samart"},
{"name":"Welch Frascone"},
{"name":"Patin Raybould"},
{"name":"Kirbie Dibdin"},
{"name":"Manon Matzen"},
{"name":"Cammi Bakster"},
{"name":"Aleen Goddert.sf"},
{"name":"Huey Feldheim"},
{"name":"Maxy Procter"},
{"name":"Sig Hacard"},
{"name":"Nydia Hardson"},
{"name":"Fredrick Anniwell"},
{"name":"Sigismundo Mattosoff"},
{"name":"Hurlee Brims"},
{"name":"Natalina Petzold"},
{"name":"Binky Lillie"},
{"name":"Barnett Clemenzi"},
{"name":"Gordie Cometson"},
{"name":"Tyler Coleyshaw"},
{"name":"Way Gai"},
{"name":"Rozanna Rugge"},
{"name":"Liliane Marousek"},
{"name":"Sherrie Goold"},
{"name":"Kate Shekle"},
{"name":"Gabi Cabral"},
{"name":"Eldon Morter"},
{"name":"Eugenie Kaplin"},
{"name":"Jeannie Forsdyke"},
{"name":"West Paulus"},
{"name":"Iris Loidl"},
{"name":"Ewart Rallinshaw"},
{"name":"Nickie Reavell"},
{"name":"Justinian Pettyfar"},
{"name":"Brooks Ledram"},
{"name":"Laird Sarle"},
{"name":"Fina Quaife"},
{"name":"Elysee Trevaskiss"},
{"name":"Shannon Daniellot"},
{"name":"Woody Taylerson"},
{"name":"Dame Jarmain"},
{"name":"Lorne Paschke"},
{"name":"Brice Bessell"},
{"name":"Crysta Roddan"},
{"name":"Tris Hartless"},
{"name":"Trueman McAvin"},
{"name":"Maressa Josefsen"},
{"name":"Pennie Caplen"},
{"name":"Claresta O'Loughane"},
{"name":"Verile Wingeat"},
{"name":"Markus Eltringham"},
{"name":"Rheta Starr"},
{"name":"Coraline Gayler"},
{"name":"Essa Collacombe"},
{"name":"Fionna Denisevich"},
{"name":"Lauraine Murphy"},
{"name":"Karee Dumbarton"},
{"name":"Cyb Eles"},
{"name":"Augustine Skey"},
{"name":"Ezmeralda Verrall"},
{"name":"Kippy Gartland"},
{"name":"Ashley Gotobed"},
{"name":"Charmion Larner"},
{"name":"Miriam Gounet"},
{"name":"Field McKinnon"},
{"name":"Yalonda Luciano"},
{"name":"Tobiah Tubritt"},
{"name":"Guinevere Gheorghescu"},
{"name":"Brockie McGrowther"},
{"name":"Yehudit Lethem"},
{"name":"Aili Stoffel"},
{"name":"Rosita Capitano"},
{"name":"Lanny Corrado"},
{"name":"Noland Chester"},
{"name":"Janine Napper"},
{"name":"Kimberley Colebourn"},
{"name":"Hammad Freeburn"},
{"name":"Elka Dunning"},
{"name":"Alisha Peyro"},
{"name":"Morey Follit"},
{"name":"Debee Mason"},
{"name":"Langsdon Fussey"},
{"name":"Crosby Tolerton"},
{"name":"Osgood Ouldred"},
{"name":"Jacki Doag"},
{"name":"Fanchette Thurlborn"},
{"name":"Glen Janaszewski"},
{"name":"Wanda Hylands"},
{"name":"Care Spinley"},
{"name":"Mayne Himpson"},
{"name":"Raviv Squires"},
{"name":"Weston Windsor"},
{"name":"Catlee Pitkaithly"},
{"name":"Bern Clewer"},
{"name":"Anson Helstrip"},
{"name":"Raphael Troy"},
{"name":"Ulises Beaze"},
{"name":"Maggy Radbond"},
{"name":"Emyle Pyle"},
{"name":"Essie Mecco"},
{"name":"Stanislaus Burgoin"},
{"name":"Brad Diem"},
{"name":"Marleen Armiger"},
{"name":"Marley Cassley"},
{"name":"Kippie Duggen"},
{"name":"Dalenna Pleuman"},
{"name":"Vinni Winks"},
{"name":"Karina Hobbert"},
{"name":"Loise Read"},
{"name":"Wilmar Really"},
{"name":"Darcy Hirtz"},
{"name":"Hector Benneyworth"},
{"name":"Adolphe Petrovic"},
{"name":"Fowler Bartoletti"},
{"name":"Talbot Ridolfi"},
{"name":"Elayne Glasser"},
{"name":"Cindi Seabright"},
{"name":"Egbert Haly"},
{"name":"Denna Frederick"},
{"name":"Chaunce Mulvin"},
{"name":"Cecil Keyson"},
{"name":"Gayle Tofpik"},
{"name":"Cariotta Parkhouse"},
{"name":"Jere Dewen"},
{"name":"Arluene Heyward"},
{"name":"Nanete Vickarman"},
{"name":"Andros Oxshott"},
{"name":"Mariana Wasselin"},
{"name":"Ella Skepper"},
{"name":"Brnaby Yokel"},
{"name":"Neala Fleisch"},
{"name":"Liana Daulby"},
{"name":"Antonina Weinberg"},
{"name":"Averell Prout"},
{"name":"Dag Pernell"},
{"name":"Shannen Eveque"},
{"name":"Alvy Albrecht"},
{"name":"Basile Murrhaupt"},
{"name":"Zena Glozman"},
{"name":"Devland Gooms"},
{"name":"Rayner Richardson"},
{"name":"Wash Trenholme"},
{"name":"Agathe O'Corrane"},
{"name":"Isadora Bloys"},
{"name":"Simon McFadin"},
{"name":"Demeter Hagwood"},
{"name":"Jaquelyn Mengue"},
{"name":"Kelsey Vanezis"},
{"name":"Stephana McConnal"},
{"name":"Carlene Dunbleton"},
{"name":"Corrie Roser"},
{"name":"Ferrel Cadamy"},
{"name":"Reidar Glidden"},
{"name":"Shane Macknish"},
{"name":"Renelle Gilvary"},
{"name":"Sigvard Dibb"},
{"name":"Eldredge Pinare"},
{"name":"Burt Duffyn"},
{"name":"Claudianus Feehily"},
{"name":"Whitman Bonnick"},
{"name":"Gus Dutnell"},
{"name":"Sylvia Haquard"},
{"name":"Ynez Stallybrass"},
{"name":"Brady Giraudel"},
{"name":"Ichabod Revens"},
{"name":"Ynes Richold"},
{"name":"Cleavland Anthon"},
{"name":"Shalom Kennard"},
{"name":"Sabrina Hacksby"},
{"name":"Wayne Websdale"},
{"name":"Terencio Lyttle"},
{"name":"Phelia Scarsbrooke"},
{"name":"Gwenneth Tinman"},
{"name":"Dee dee Bemment"},
{"name":"Constancy Bodley"},
{"name":"Jori Ecclestone"},
{"name":"Eldin Tatters"},
{"name":"Giffy Heaviside"},
{"name":"Adrian Braund"},
{"name":"Wenonah Stancliffe"},
{"name":"Polly Newberry"},
{"name":"Milzie Spiller"},
{"name":"Hedda Woodroffe"},
{"name":"Jemima Stappard"},
{"name":"Odilia Elsey"},
{"name":"Hussein Dow"},
{"name":"Sydelle Balleine"},
{"name":"Clementia Ransbury"},
{"name":"Pamelina Crose"},
{"name":"Carmine Archambault"},
{"name":"Vivianne Robjents"},
{"name":"Ulberto Lepper"},
{"name":"Petrina Brace"},
{"name":"Diane Cockroft"},
{"name":"Rosina O'Connell"},
{"name":"Rivalee Oven"},
{"name":"Kasey Quickenden"},
{"name":"Lorette Wassell"},
{"name":"Haze Kunzel"},
{"name":"Henry Cann"},
{"name":"Alessandro Straneo"},
{"name":"Gennie Slyman"},
{"name":"Shermie Biaggioni"},
{"name":"Kristan Barnewelle"},
{"name":"Brigham Hefferon"},
{"name":"Winona Kelberer"},
{"name":"Darby Liepina"},
{"name":"Eleen Lammenga"},
{"name":"Lorrayne Guillotin"},
{"name":"Nadiya Gladyer"},
{"name":"Hercule Crut"},
{"name":"Jillene Pidgin"},
{"name":"Christie Nisius"},
{"name":"Elysee Kimble"},
{"name":"Laurens Tullett"},
{"name":"Ruthanne Clemson"},
{"name":"Annalise Atwell"},
{"name":"Elsinore Caren"},
{"name":"Margeaux Lissaman"},
{"name":"Pieter Yurasov"},
{"name":"Hi Boanas"},
{"name":"Alfreda Elvins"},
{"name":"Winthrop Yonge"},
{"name":"Shaina Derle"},
{"name":"Kassey Ghiraldi"},
{"name":"Kimberlee Lockie"},
{"name":"Ezequiel Drysdell"},
{"name":"Gaye Downgate"},
{"name":"Karole McEnery"},
{"name":"Danyelle Birdseye"},
{"name":"Muire Cronin"},
{"name":"Elisha Trenbay"},
{"name":"Stevana Paulisch"},
{"name":"Tabb Le Gallo"},
{"name":"Gwyn Poll"},
{"name":"Darya Kielt"},
{"name":"Adria Rosenbusch"},
{"name":"Hagen Bushel"},
{"name":"Ynez Garrand"},
{"name":"Wenona Rous"},
{"name":"Gertrud Forrest"},
{"name":"Elisha Baggalley"},
{"name":"Damita Haack"},
{"name":"Heddi Rennard"},
{"name":"Jeannette Lathom"},
{"name":"Morton Trayhorn"},
{"name":"Alistair Salery"},
{"name":"Gillian Sarl"},
{"name":"Skyler Rubinshtein"},
{"name":"Simone L'oiseau"},
{"name":"Ogdon Ginnane"},
{"name":"Marcia Stockau"},
{"name":"Alastair Bosden"},
{"name":"Biron Swithenby"},
{"name":"Kiley McCafferky"},
{"name":"Andrew Singers"},
{"name":"Darryl Snelman"},
{"name":"Olivia Smout"},
{"name":"Reinald Keeffe"},
{"name":"Phyllis Wyett"},
{"name":"Britt Puckey"},
{"name":"Tadio Van Son"},
{"name":"Ase Westcarr"},
{"name":"Beauregard Tuther"},
{"name":"Erv Niccolls"},
{"name":"Hyacinth Godlee"},
{"name":"Alanah Yewman"},
{"name":"Eddy Bettlestone"},
{"name":"Mohammed Rozycki"},
{"name":"Yolande Swetenham"},
{"name":"Freddie Skittrell"},
{"name":"Elmo Olpin"},
{"name":"Nolan Tallon"},
{"name":"Shawnee Rylance"},
{"name":"Maxi Sewill"},
{"name":"Marci Huckett"},
{"name":"Amitie Droogan"},
{"name":"Miriam Van Hesteren"},
{"name":"Gerard Breitling"},
{"name":"Norbie Tart"},
{"name":"Joaquin Stonner"},
{"name":"Joyous Davidovics"},
{"name":"Caresse McCaig"},
{"name":"Clareta Beckwith"},
{"name":"Berny Howis"},
{"name":"Jan Milch"},
{"name":"Michaeline Dobbson"},
{"name":"Amber McKimm"},
{"name":"Wheeler Fenich"},
{"name":"Emmit Geelan"},
{"name":"Othilie Espinha"},
{"name":"Lauree Noads"},
{"name":"Opalina Volcker"},
{"name":"Elisabetta Dines"},
{"name":"Hunfredo McQuilkin"},
{"name":"Lishe Costelloe"},
{"name":"Cassandra Abercromby"},
{"name":"Ajay Dabs"},
{"name":"Dyanne Wick"},
{"name":"Monroe Downton"},
{"name":"Sheelagh Chudleigh"},
{"name":"Ingram Hedditeh"},
{"name":"Virgie Sedgwick"},
{"name":"Moore McDowall"},
{"name":"Bryan Chater"},
{"name":"Marnia Edmondson"},
{"name":"Yvonne Danilyak"},
{"name":"Pauline Bootherstone"},
{"name":"Darrelle Yankin"},
{"name":"Daria Betser"},
{"name":"Wilone Revie"},
{"name":"Floris Eede"},
{"name":"Kali Nansom"},
{"name":"Lyell Benda"},
{"name":"Anni Langtry"},
{"name":"Ulberto Gauntlett"},
{"name":"Fania Pimblett"},
{"name":"Flore Grinsdale"},
{"name":"Manya Lukianovich"},
{"name":"Tobin Cribbott"},
{"name":"Germain Gorwood"},
{"name":"Ryley Santino"},
{"name":"Hedda Feast"},
{"name":"Jere Tytherton"},
{"name":"Welbie Summerson"},
{"name":"Constantin Siberry"},
{"name":"Joshuah Moret"},
{"name":"Marion Forsaith"},
{"name":"Cori Boydle"},
{"name":"Mayor Leward"},
{"name":"Abbe Byers"},
{"name":"Andras Ornils"},
{"name":"Christoffer Cronin"},
{"name":"Bailie Yuryshev"},
{"name":"Dela Fellibrand"},
{"name":"Edita Cree"},
{"name":"Korrie Lewerenz"},
{"name":"Matias Skrine"},
{"name":"Stan Darker"},
{"name":"Ericka Debling"},
{"name":"Vanya Henric"},
{"name":"Brynne Stanley"},
{"name":"Tressa Godfree"},
{"name":"Sarena Whisson"},
{"name":"Melvyn Ingreda"},
{"name":"Harwilll Antoniewicz"},
{"name":"Eunice Kembry"},
{"name":"Ileana Sancraft"},
{"name":"Karin Geffinger"},
{"name":"Renae Clarabut"},
{"name":"Philippine Healy"},
{"name":"Nappie Killigrew"},
{"name":"Sullivan Gadesby"},
{"name":"Fionnula Dooney"},
{"name":"Wendel Cappleman"},
{"name":"Cati Dalrymple"},
{"name":"Franciska Mouatt"},
{"name":"Winona Eamer"},
{"name":"Georgie Melvin"},
{"name":"Hanan Hirsthouse"},
{"name":"Ravid Keir"},
{"name":"Neddy Vyse"},
{"name":"Brade Tucsell"},
{"name":"Delores Lissaman"},
{"name":"Nikolai Van Haeften"},
{"name":"Poul Saggs"},
{"name":"Benjie Minards"},
{"name":"Kristine Aslin"},
{"name":"Tiphany O'Doran"},
{"name":"Broddie Peirson"},
{"name":"Tremayne Darbishire"},
{"name":"Mandie Newis"},
{"name":"Thatcher Shevelin"},
{"name":"Loella Lavington"},
{"name":"Mathias Cordingley"},
{"name":"Corney Lukovic"},
{"name":"Vernor Colquit"},
{"name":"Arline Episcopi"},
{"name":"Kiley Gabe"},
{"name":"Nataline Knowlton"},
{"name":"Selie Ridesdale"},
{"name":"Lock Switzer"},
{"name":"Allx Stockhill"},
{"name":"Hunfredo Yerson"},
{"name":"Delmer Burwell"},
{"name":"Kalinda Pulham"},
{"name":"Angelina McClinton"},
{"name":"Louella Nursey"},
{"name":"Mindy Gooddie"},
{"name":"Frankie Iacabucci"},
{"name":"Dre Caulton"},
{"name":"Duff Erskine"},
{"name":"Paddy Doughton"},
{"name":"Fabio Burriss"},
{"name":"Gaspar Jerrand"},
{"name":"Leyla Simonnot"},
{"name":"Aeriel Boutell"},
{"name":"Jozef Grinishin"},
{"name":"Guillemette Braz"},
{"name":"Amaleta Porcas"},
{"name":"Chaddie Dimitriades"},
{"name":"Whittaker Saiger"},
{"name":"Rurik Batts"},
{"name":"Jacquetta Skillman"},
{"name":"Sanders Alldis"},
{"name":"Vilma St Louis"},
{"name":"Filide MacGinley"},
{"name":"Wallas Harbor"},
{"name":"Richardo Headan"},
{"name":"Missie McCully"},
{"name":"Lianne Talman"},
{"name":"Bernadene Adamczyk"},
{"name":"Alfred Zorzoni"},
{"name":"Tiffanie Hemerijk"},
{"name":"Judye Dumingos"},
{"name":"Vanni Rubi"},
{"name":"Nerissa Took"},
{"name":"Gerardo Raffeorty"},
{"name":"Freemon Griffitt"},
{"name":"Lorilyn Lowndsbrough"},
{"name":"Rosanna Basham"},
{"name":"Clarabelle Archbald"},
{"name":"Phillipp Aymeric"},
{"name":"Ema Vidyapin"},
{"name":"Travis Hallatt"},
{"name":"Dael Stebbing"},
{"name":"Winifield Poplee"},
{"name":"Marian Paice"},
{"name":"Megan Ibarra"},
{"name":"Sylvan Dunaway"},
{"name":"Lisle Gannon"},
{"name":"Linell Amor"},
{"name":"Adore Sissons"},
{"name":"Brietta Nisbith"},
{"name":"Anissa Fursey"},
{"name":"Devondra Tutt"},
{"name":"Kath Rae"},
{"name":"Emelyne Jaffray"},
{"name":"Eda Scully"},
{"name":"Roxanne Butfield"},
{"name":"Lon Blackater"},
{"name":"Ofella Oloman"},
{"name":"Ailsun Wurst"},
{"name":"Rosina Spurway"},
{"name":"Burch Prinne"},
{"name":"Josephina Skellen"},
{"name":"Keely Penrose"},
{"name":"Faythe Vance"},
{"name":"Kristofer Parslow"},
{"name":"Noella Zavattieri"},
{"name":"Patricio McQuarrie"},
{"name":"Mariele Gravett"},
{"name":"Dacey Trewartha"},
{"name":"Didi Verchambre"},
{"name":"Lancelot Brayshaw"},
{"name":"Katleen Pudge"},
{"name":"Flemming Schultes"},
{"name":"Aubry Lambswood"},
{"name":"Prent Thain"},
{"name":"Josias Bagworth"},
{"name":"Josselyn Forrington"},
{"name":"Zsazsa Blunsen"},
{"name":"Toni Mulderrig"},
{"name":"Rosie McKelvey"},
{"name":"Nickie Bispham"},
{"name":"Ermentrude Libby"},
{"name":"Reiko Daniaud"},
{"name":"Stephan Coper"},
{"name":"Franciska Sears"},
{"name":"Francisca Vertigan"},
{"name":"Riccardo Redwood"},
{"name":"Minnie Hughesdon"},
{"name":"Lou Malley"},
{"name":"Nicoline Volleth"},
{"name":"Humfrey Schonfelder"},
{"name":"Paddy Seggie"},
{"name":"Lion Rawes"},
{"name":"Mikol Rapps"},
{"name":"Valentino Laborde"},
{"name":"Klarrisa Baumert"},
{"name":"Wylie Ibbison"},
{"name":"Mahmud Tackett"},
{"name":"Marlowe Poynor"},
{"name":"Dorian Djorevic"},
{"name":"Frances Skipper"},
{"name":"Meridel Neve"},
{"name":"Suzanna Caltun"},
{"name":"Analiese MacFadin"},
{"name":"Shalne Gaymar"},
{"name":"Ronald Elsy"},
{"name":"Halley Laurens"},
{"name":"Prent Ceaplen"},
{"name":"Lurette Fillon"},
{"name":"Josi Meechan"},
{"name":"Joly Simms"},
{"name":"Lombard O' Donohue"},
{"name":"Benjie MacCole"},
{"name":"Lowe MacAndie"},
{"name":"Matelda Whiteson"},
{"name":"Haven Bellord"},
{"name":"Wendye Vasilik"},
{"name":"Devy Siebert"},
{"name":"Teressa Townby"},
{"name":"Tanya But"},
{"name":"Sashenka Stonner"},
{"name":"Judi Spooner"},
{"name":"Petra Babon"},
{"name":"Stella Brash"},
{"name":"Nicoli Di Maria"},
{"name":"Guenevere Checchi"},
{"name":"Elsinore McCreary"},
{"name":"Dov Povlsen"},
{"name":"Hilary Becarra"},
{"name":"Brant Kaubisch"},
{"name":"Zandra Mozzi"},
{"name":"Sidney Lawfull"},
{"name":"Sheffield Barnson"},
{"name":"Frederick Chirm"},
{"name":"Jacquie Andrick"},
{"name":"Ulrica Duhig"},
{"name":"Adorne Otham"},
{"name":"Tracee Templar"},
{"name":"Anna-diana Clac"},
{"name":"Forester Haffard"},
{"name":"Roxine Fidelus"},
{"name":"Devonne McLeod"},
{"name":"Laughton Illem"},
{"name":"Albertine Gimson"},
{"name":"Stanly Proschek"},
{"name":"Eolanda Huffy"},
{"name":"Harriott Dedenham"},
{"name":"Alick Symonds"},
{"name":"Winonah Warsop"},
{"name":"Luis Shasnan"},
{"name":"Gisella Borgne"},
{"name":"Mariam Blakeway"},
{"name":"Mavis Birth"},
{"name":"Vaughn Habron"},
{"name":"Brandise Skule"},
{"name":"Sayres Ridoutt"},
{"name":"Sarene Sallery"},
{"name":"Odella Leaman"},
{"name":"Merna Banbrook"},
{"name":"Brodie Megroff"},
{"name":"Blair Loins"},
{"name":"Virgilio Tomisch"},
{"name":"Terry Caesar"},
{"name":"Lemuel Hlavecek"},
{"name":"Hervey Stains"},
{"name":"Rosaline Haugen"},
{"name":"Nappie Surridge"},
{"name":"Norton Lathaye"},
{"name":"Ailey Bitchener"},
{"name":"Miller Rumke"},
{"name":"Marci Jehan"},
{"name":"Ludvig Czyz"},
{"name":"Jan Askey"},
{"name":"Guillaume Ekkel"},
{"name":"Ashia Lethlay"},
{"name":"Daryle Rainger"},
{"name":"Wilmar Headly"},
{"name":"Verina Orr"},
{"name":"Britte Siss"}]
names = [name["name"] for name in names]

orgs = [{"org":"Flashdog"},
{"org":"Browsecat"},
{"org":"Avaveo"},
{"org":"Yodel"},
{"org":"Zooxo"},
{"org":"Bubblebox"},
{"org":"Dablist"},
{"org":"Twitternation"},
{"org":"Yakidoo"},
{"org":"Ooba"},
{"org":"Voomm"},
{"org":"Flashspan"},
{"org":"Topicstorm"},
{"org":"Yotz"},
{"org":"Brainbox"},
{"org":"Mymm"},
{"org":"Yodel"},
{"org":"Mymm"},
{"org":"Meeveo"},
{"org":"Plajo"},
{"org":"Feedfire"},
{"org":"Zazio"},
{"org":"Voonyx"},
{"org":"Babblestorm"},
{"org":"Yodel"},
{"org":"Oloo"},
{"org":"Browsetype"},
{"org":"Kanoodle"},
{"org":"Gabcube"},
{"org":"Mudo"},
{"org":"Ozu"},
{"org":"Skalith"},
{"org":"Quatz"},
{"org":"Twinder"},
{"org":"Jaxnation"},
{"org":"Bubblebox"},
{"org":"InnoZ"},
{"org":"Buzzshare"},
{"org":"Midel"},
{"org":"Vinder"},
{"org":"LiveZ"},
{"org":"Reallinks"},
{"org":"Oodoo"},
{"org":"LiveZ"},
{"org":"Tavu"},
{"org":"Eamia"},
{"org":"Divavu"},
{"org":"Eadel"},
{"org":"Skynoodle"},
{"org":"Voonyx"},
{"org":"Oyoloo"},
{"org":"Tanoodle"},
{"org":"Realbuzz"},
{"org":"Skiptube"},
{"org":"Riffwire"},
{"org":"Edgetag"},
{"org":"Jamia"},
{"org":"Realfire"},
{"org":"Gabvine"},
{"org":"Npath"},
{"org":"Jabberstorm"},
{"org":"Shufflebeat"},
{"org":"Trupe"},
{"org":"Jetwire"},
{"org":"Thoughtmix"},
{"org":"Meedoo"},
{"org":"Ainyx"},
{"org":"Jabbertype"},
{"org":"Wordware"},
{"org":"Blogtag"},
{"org":"Trupe"},
{"org":"Skyba"},
{"org":"Teklist"},
{"org":"Skimia"},
{"org":"Fivespan"},
{"org":"Skajo"},
{"org":"Gevee"},
{"org":"Zoonder"},
{"org":"Gabtype"},
{"org":"Zoombeat"},
{"org":"Ailane"},
{"org":"Tekfly"},
{"org":"Yakidoo"},
{"org":"Ntag"},
{"org":"Gigazoom"},
{"org":"Vimbo"},
{"org":"Wordtune"},
{"org":"Fanoodle"},
{"org":"Fivespan"},
{"org":"Voolith"},
{"org":"Kamba"},
{"org":"Jazzy"},
{"org":"Dynabox"},
{"org":"Abata"},
{"org":"Layo"},
{"org":"Cogilith"},
{"org":"Jayo"},
{"org":"Trudeo"},
{"org":"Kamba"},
{"org":"Gigazoom"},
{"org":"Zava"},
{"org":"Trilia"},
{"org":"Wikido"},
{"org":"Meetz"},
{"org":"Jabbercube"},
{"org":"Cogibox"},
{"org":"Topdrive"},
{"org":"Brainlounge"},
{"org":"Yodo"},
{"org":"Pixonyx"},
{"org":"Skaboo"},
{"org":"Vidoo"},
{"org":"Quaxo"},
{"org":"Tagopia"},
{"org":"Topicblab"},
{"org":"Skidoo"},
{"org":"Voonte"},
{"org":"Youspan"},
{"org":"Quinu"},
{"org":"Ainyx"},
{"org":"Cogibox"},
{"org":"Snaptags"},
{"org":"Pixonyx"},
{"org":"InnoZ"},
{"org":"Brainbox"},
{"org":"Yotz"},
{"org":"Voolia"},
{"org":"Yadel"},
{"org":"Cogidoo"},
{"org":"Skyvu"},
{"org":"Skibox"},
{"org":"Feedbug"},
{"org":"Roombo"},
{"org":"Zazio"},
{"org":"Oyope"},
{"org":"Zooveo"},
{"org":"Tagpad"},
{"org":"Thoughtstorm"},
{"org":"Riffpedia"},
{"org":"Einti"},
{"org":"Voomm"},
{"org":"Gigashots"},
{"org":"Blogtags"},
{"org":"Digitube"},
{"org":"LiveZ"},
{"org":"Youfeed"},
{"org":"Oyope"},
{"org":"Twiyo"},
{"org":"Dabshots"},
{"org":"Skyble"},
{"org":"Izio"},
{"org":"Tagchat"},
{"org":"Thoughtworks"},
{"org":"Jabberstorm"},
{"org":"Yakijo"},
{"org":"Demimbu"},
{"org":"Rhybox"},
{"org":"Snaptags"},
{"org":"Zoomcast"},
{"org":"Skidoo"},
{"org":"Yakitri"},
{"org":"Tanoodle"},
{"org":"Fadeo"},
{"org":"Realblab"},
{"org":"Dabfeed"},
{"org":"Kwinu"},
{"org":"Skyndu"},
{"org":"Zoomdog"},
{"org":"Feedspan"},
{"org":"Yotz"},
{"org":"Quatz"},
{"org":"Jaxnation"},
{"org":"Cogilith"},
{"org":"Vinder"},
{"org":"Fivespan"},
{"org":"Vimbo"},
{"org":"Tazz"},
{"org":"Kanoodle"},
{"org":"Youspan"},
{"org":"Quimm"},
{"org":"Yodoo"},
{"org":"Wordware"},
{"org":"Edgeblab"},
{"org":"Vinder"},
{"org":"Jaloo"},
{"org":"Linkbridge"},
{"org":"Viva"},
{"org":"Jazzy"},
{"org":"Midel"},
{"org":"Jayo"},
{"org":"Twimbo"},
{"org":"Lajo"},
{"org":"Avavee"},
{"org":"Kimia"},
{"org":"Yata"},
{"org":"Shuffledrive"},
{"org":"Cogidoo"},
{"org":"Kwimbee"},
{"org":"Jayo"},
{"org":"Realfire"},
{"org":"Zoomlounge"},
{"org":"Brainverse"},
{"org":"Gabtype"},
{"org":"Vimbo"},
{"org":"Yodel"},
{"org":"Gabcube"},
{"org":"Trunyx"},
{"org":"Browseblab"},
{"org":"Kwinu"},
{"org":"Katz"},
{"org":"Yata"},
{"org":"Quatz"},
{"org":"Photobean"},
{"org":"Livefish"},
{"org":"Youtags"},
{"org":"Avavee"},
{"org":"Realfire"},
{"org":"Thoughtsphere"},
{"org":"Edgeblab"},
{"org":"Ntag"},
{"org":"Lazz"},
{"org":"Mybuzz"},
{"org":"Edgeblab"},
{"org":"Kimia"},
{"org":"Linkbuzz"},
{"org":"Zoonoodle"},
{"org":"Digitube"},
{"org":"Riffpedia"},
{"org":"Mycat"},
{"org":"Skidoo"},
{"org":"Aivee"},
{"org":"Youspan"},
{"org":"Livetube"},
{"org":"Realbuzz"},
{"org":"Quatz"},
{"org":"Dabvine"},
{"org":"Izio"},
{"org":"Pixope"},
{"org":"Ozu"},
{"org":"Dabtype"},
{"org":"Skinder"},
{"org":"Realcube"},
{"org":"Yodel"},
{"org":"Wordify"},
{"org":"Avamba"},
{"org":"Voolith"},
{"org":"Shuffledrive"},
{"org":"DabZ"},
{"org":"Bubblemix"},
{"org":"Gevee"},
{"org":"Dynabox"},
{"org":"Edgeclub"},
{"org":"Photofeed"},
{"org":"Flashpoint"},
{"org":"Zoomzone"},
{"org":"Meemm"},
{"org":"Divavu"},
{"org":"Zoomlounge"},
{"org":"Shufflebeat"},
{"org":"Devcast"},
{"org":"Jazzy"},
{"org":"Topicstorm"},
{"org":"Yakidoo"},
{"org":"Browsetype"},
{"org":"Flashspan"},
{"org":"Flipopia"},
{"org":"Oyondu"},
{"org":"Riffpath"},
{"org":"Npath"},
{"org":"Zazio"},
{"org":"Jatri"},
{"org":"Flipopia"},
{"org":"Wikido"},
{"org":"Centidel"},
{"org":"Twinte"},
{"org":"Zoozzy"},
{"org":"Yozio"},
{"org":"Abata"},
{"org":"Trudoo"},
{"org":"Digitube"},
{"org":"Ozu"},
{"org":"Blogpad"},
{"org":"Gigazoom"},
{"org":"Divanoodle"},
{"org":"Zoonder"},
{"org":"Voonyx"},
{"org":"Demimbu"},
{"org":"Bluejam"},
{"org":"Dablist"},
{"org":"Cogidoo"},
{"org":"Abata"},
{"org":"Zava"},
{"org":"Wikizz"},
{"org":"Twinder"},
{"org":"Devpoint"},
{"org":"Buzzster"},
{"org":"Plambee"},
{"org":"Roomm"},
{"org":"Trudeo"},
{"org":"Yadel"},
{"org":"Browsetype"},
{"org":"Viva"},
{"org":"Skibox"},
{"org":"Viva"},
{"org":"Vimbo"},
{"org":"Eazzy"},
{"org":"Vimbo"},
{"org":"Eimbee"},
{"org":"Dynava"},
{"org":"Brainverse"},
{"org":"Brainsphere"},
{"org":"Mudo"},
{"org":"Flashpoint"},
{"org":"Blogtags"},
{"org":"Yozio"},
{"org":"Blogtag"},
{"org":"Realmix"},
{"org":"Skiba"},
{"org":"Tagopia"},
{"org":"Youspan"},
{"org":"Jaxspan"},
{"org":"Kazio"},
{"org":"Innojam"},
{"org":"Cogidoo"},
{"org":"Twitterbridge"},
{"org":"Eimbee"},
{"org":"Bubbletube"},
{"org":"Gabtune"},
{"org":"Blogtags"},
{"org":"Gabvine"},
{"org":"Tanoodle"},
{"org":"Flashpoint"},
{"org":"Quamba"},
{"org":"Geba"},
{"org":"Skyble"},
{"org":"Meezzy"},
{"org":"LiveZ"},
{"org":"Leenti"},
{"org":"Gevee"},
{"org":"Browseblab"},
{"org":"Janyx"},
{"org":"Jabbertype"},
{"org":"Rhycero"},
{"org":"Thoughtblab"},
{"org":"Dabshots"},
{"org":"Kazu"},
{"org":"Fliptune"},
{"org":"Jabbercube"},
{"org":"Quinu"},
{"org":"Rhynyx"},
{"org":"Kaymbo"},
{"org":"Eimbee"},
{"org":"Eadel"},
{"org":"Jayo"},
{"org":"Trudoo"},
{"org":"Photolist"},
{"org":"Realfire"},
{"org":"Feednation"},
{"org":"Flipbug"},
{"org":"Topiczoom"},
{"org":"Brainverse"},
{"org":"Kwilith"},
{"org":"Dabvine"},
{"org":"Skaboo"},
{"org":"Topiczoom"},
{"org":"Tekfly"},
{"org":"Meedoo"},
{"org":"Quimm"},
{"org":"Browsebug"},
{"org":"Jabberstorm"},
{"org":"Roomm"},
{"org":"Shuffledrive"},
{"org":"Realfire"},
{"org":"Buzzdog"},
{"org":"Flipstorm"},
{"org":"Fanoodle"},
{"org":"Yoveo"},
{"org":"Talane"},
{"org":"Eamia"},
{"org":"Voonyx"},
{"org":"Jayo"},
{"org":"Miboo"},
{"org":"Tagopia"},
{"org":"Bubblebox"},
{"org":"Feedfish"},
{"org":"Gigazoom"},
{"org":"Kwideo"},
{"org":"Yakidoo"},
{"org":"Viva"},
{"org":"Edgeify"},
{"org":"Flipstorm"},
{"org":"Centimia"},
{"org":"Feednation"},
{"org":"Shuffledrive"},
{"org":"Livetube"},
{"org":"Gigazoom"},
{"org":"Flipopia"},
{"org":"Vinte"},
{"org":"Vinder"},
{"org":"Tagcat"},
{"org":"Demivee"},
{"org":"Zoomdog"},
{"org":"Flashspan"},
{"org":"JumpXS"},
{"org":"Ooba"},
{"org":"Skajo"},
{"org":"Wordtune"},
{"org":"Realblab"},
{"org":"Abatz"},
{"org":"Skajo"},
{"org":"Layo"},
{"org":"Ainyx"},
{"org":"Meeveo"},
{"org":"Thoughtblab"},
{"org":"Omba"},
{"org":"Livepath"},
{"org":"Mynte"},
{"org":"Devpulse"},
{"org":"Eire"},
{"org":"Kwilith"},
{"org":"Babbleset"},
{"org":"Skyba"},
{"org":"Meembee"},
{"org":"Skajo"},
{"org":"Zava"},
{"org":"Zoonoodle"},
{"org":"Youopia"},
{"org":"Skalith"},
{"org":"Brainbox"},
{"org":"Rooxo"},
{"org":"Voonix"},
{"org":"Zoombox"},
{"org":"Mita"},
{"org":"Brainlounge"},
{"org":"Babbleset"},
{"org":"Skyba"},
{"org":"Meezzy"},
{"org":"Chatterpoint"},
{"org":"Meejo"},
{"org":"Agivu"},
{"org":"Gabtune"},
{"org":"Devpulse"},
{"org":"Quire"},
{"org":"Brainverse"},
{"org":"Twinte"},
{"org":"Demimbu"},
{"org":"Flipstorm"},
{"org":"Topiclounge"},
{"org":"Rhyloo"},
{"org":"Voomm"},
{"org":"Devpoint"},
{"org":"Topdrive"},
{"org":"Quatz"},
{"org":"Brainbox"},
{"org":"Rhybox"},
{"org":"Twitterbeat"},
{"org":"Agivu"},
{"org":"Twinder"},
{"org":"Blogpad"},
{"org":"Topdrive"},
{"org":"Flashset"},
{"org":"Cogilith"},
{"org":"Einti"},
{"org":"Kanoodle"},
{"org":"Kanoodle"},
{"org":"Quinu"},
{"org":"Devify"},
{"org":"Yakijo"},
{"org":"Brightbean"},
{"org":"Twinder"},
{"org":"Meevee"},
{"org":"Layo"},
{"org":"Fivechat"},
{"org":"Janyx"},
{"org":"Dabvine"},
{"org":"Linktype"},
{"org":"Dablist"},
{"org":"Yombu"},
{"org":"Innojam"},
{"org":"Eamia"},
{"org":"Myworks"},
{"org":"Agivu"},
{"org":"Rhycero"},
{"org":"Tambee"},
{"org":"Ainyx"},
{"org":"Twiyo"},
{"org":"Aimbu"},
{"org":"Tagopia"},
{"org":"Devcast"},
{"org":"Photobug"},
{"org":"Skyndu"},
{"org":"Innojam"},
{"org":"Aivee"},
{"org":"Agimba"},
{"org":"Eamia"},
{"org":"Myworks"},
{"org":"Dablist"},
{"org":"Wikizz"},
{"org":"Dazzlesphere"},
{"org":"Babbleopia"},
{"org":"Realpoint"},
{"org":"Pixoboo"},
{"org":"Meejo"},
{"org":"Edgepulse"},
{"org":"Skajo"},
{"org":"Ntag"},
{"org":"Lazz"},
{"org":"Trudoo"},
{"org":"Dynazzy"},
{"org":"Gigazoom"},
{"org":"Tazz"},
{"org":"Browsecat"},
{"org":"Pixonyx"},
{"org":"Dynava"},
{"org":"Demimbu"},
{"org":"Aimbo"},
{"org":"Innotype"},
{"org":"BlogXS"},
{"org":"Jabbertype"},
{"org":"Kayveo"},
{"org":"InnoZ"},
{"org":"Trudoo"},
{"org":"Jaloo"},
{"org":"Divape"},
{"org":"Blognation"},
{"org":"Mynte"},
{"org":"Skinte"},
{"org":"Roomm"},
{"org":"Tanoodle"},
{"org":"Aibox"},
{"org":"Myworks"},
{"org":"Dazzlesphere"},
{"org":"Yodoo"},
{"org":"Ainyx"},
{"org":"Tanoodle"},
{"org":"Ooba"},
{"org":"Yotz"},
{"org":"Eidel"},
{"org":"Browsetype"},
{"org":"Twimbo"},
{"org":"Wordify"},
{"org":"Tagpad"},
{"org":"Skajo"},
{"org":"Yozio"},
{"org":"Roomm"},
{"org":"Midel"},
{"org":"Zoomzone"},
{"org":"Geba"},
{"org":"Topicshots"},
{"org":"Topicshots"},
{"org":"Feedfire"},
{"org":"Zoombox"},
{"org":"Skyndu"},
{"org":"Fivechat"},
{"org":"Realmix"},
{"org":"Kwilith"},
{"org":"Quimba"},
{"org":"Demimbu"},
{"org":"Wikivu"},
{"org":"Rhynoodle"},
{"org":"Jabbercube"},
{"org":"Realfire"},
{"org":"Cogilith"},
{"org":"Zooxo"},
{"org":"Leexo"},
{"org":"Bluejam"},
{"org":"Wikivu"},
{"org":"Babbleset"},
{"org":"Dazzlesphere"},
{"org":"Agimba"},
{"org":"Tagpad"},
{"org":"Linktype"},
{"org":"Photolist"},
{"org":"Kimia"},
{"org":"Yamia"},
{"org":"Voonte"},
{"org":"Photofeed"},
{"org":"Shuffletag"},
{"org":"Oloo"},
{"org":"Meetz"},
{"org":"Browsecat"},
{"org":"Dabfeed"},
{"org":"Photojam"},
{"org":"Riffpath"},
{"org":"Roomm"},
{"org":"Fanoodle"},
{"org":"Oodoo"},
{"org":"LiveZ"},
{"org":"Pixoboo"},
{"org":"Linklinks"},
{"org":"Demimbu"},
{"org":"Chatterpoint"},
{"org":"Topicstorm"},
{"org":"Zoonder"},
{"org":"Kazio"},
{"org":"Avaveo"},
{"org":"Zoombeat"},
{"org":"Skinder"},
{"org":"Zoomdog"},
{"org":"Pixope"},
{"org":"Eayo"},
{"org":"Abatz"},
{"org":"Voolith"},
{"org":"Tazzy"},
{"org":"Leexo"},
{"org":"Quinu"},
{"org":"Mymm"},
{"org":"Wordify"},
{"org":"Mybuzz"},
{"org":"Centidel"},
{"org":"Divanoodle"},
{"org":"Wikizz"},
{"org":"Meejo"},
{"org":"Meetz"},
{"org":"Thoughtblab"},
{"org":"Kwinu"},
{"org":"Twimm"},
{"org":"Fiveclub"},
{"org":"Thoughtblab"},
{"org":"Dynabox"},
{"org":"Brightbean"},
{"org":"Demimbu"},
{"org":"Devbug"},
{"org":"Gabvine"},
{"org":"Trudoo"},
{"org":"Skimia"},
{"org":"Tekfly"},
{"org":"Tagopia"},
{"org":"Zoomcast"},
{"org":"Skinte"},
{"org":"Reallinks"},
{"org":"Roodel"},
{"org":"Eimbee"},
{"org":"Demimbu"},
{"org":"Mydeo"},
{"org":"Miboo"},
{"org":"Linklinks"},
{"org":"Devbug"},
{"org":"Roombo"},
{"org":"Zoombeat"},
{"org":"Talane"},
{"org":"Jaxspan"},
{"org":"Flipbug"},
{"org":"Youbridge"},
{"org":"Browsetype"},
{"org":"Eamia"},
{"org":"Lajo"},
{"org":"Thoughtmix"},
{"org":"Fanoodle"},
{"org":"Podcat"},
{"org":"Twitterbridge"},
{"org":"Devify"},
{"org":"Meemm"},
{"org":"Katz"},
{"org":"Fanoodle"},
{"org":"Wordtune"},
{"org":"Voolith"},
{"org":"Tagfeed"},
{"org":"Wikibox"},
{"org":"Meejo"},
{"org":"Flashset"},
{"org":"Shufflester"},
{"org":"Wikibox"},
{"org":"Livepath"},
{"org":"Katz"},
{"org":"Skiba"},
{"org":"Rhynoodle"},
{"org":"Quire"},
{"org":"Mydo"},
{"org":"Vimbo"},
{"org":"Mymm"},
{"org":"Gigashots"},
{"org":"Quinu"},
{"org":"Photobug"},
{"org":"Skibox"},
{"org":"Cogilith"},
{"org":"Kwimbee"},
{"org":"Kare"},
{"org":"Minyx"},
{"org":"Feedfire"},
{"org":"Omba"},
{"org":"Bubblemix"},
{"org":"Twitterbeat"},
{"org":"Linkbridge"},
{"org":"Voomm"},
{"org":"Blogspan"},
{"org":"Abatz"},
{"org":"Topicware"},
{"org":"Oodoo"},
{"org":"Innotype"},
{"org":"Riffwire"},
{"org":"Fanoodle"},
{"org":"Einti"},
{"org":"Livepath"},
{"org":"Meezzy"},
{"org":"Photobug"},
{"org":"Twimm"},
{"org":"Twitternation"},
{"org":"Topicstorm"},
{"org":"Plambee"},
{"org":"Leenti"},
{"org":"Babbleblab"},
{"org":"Podcat"},
{"org":"Voonte"},
{"org":"Pixope"},
{"org":"Twitterwire"},
{"org":"Twitterbeat"},
{"org":"Zoombeat"},
{"org":"Demivee"},
{"org":"Livetube"},
{"org":"Fivechat"},
{"org":"Dynava"},
{"org":"Gigaclub"},
{"org":"Feedfish"},
{"org":"Voonte"},
{"org":"Skajo"},
{"org":"Quamba"},
{"org":"Photobean"},
{"org":"Pixonyx"},
{"org":"Youopia"},
{"org":"Mydo"},
{"org":"Linkbuzz"},
{"org":"Mybuzz"},
{"org":"Leenti"},
{"org":"Zoonder"},
{"org":"Realbuzz"},
{"org":"Twitterworks"},
{"org":"Browsebug"},
{"org":"Ntags"},
{"org":"Topicblab"},
{"org":"Thoughtstorm"},
{"org":"Zoombeat"},
{"org":"Flipopia"},
{"org":"Oodoo"},
{"org":"Gigaclub"},
{"org":"Dabfeed"},
{"org":"Vimbo"},
{"org":"Jaloo"},
{"org":"Livefish"},
{"org":"Lajo"},
{"org":"Livetube"},
{"org":"Tagopia"},
{"org":"Photobug"},
{"org":"Devify"},
{"org":"Janyx"},
{"org":"Rhynoodle"},
{"org":"Skilith"},
{"org":"Zoonder"},
{"org":"Riffwire"},
{"org":"Youtags"},
{"org":"Browsetype"},
{"org":"Camido"},
{"org":"Skajo"},
{"org":"Twinte"},
{"org":"Realbridge"},
{"org":"Meetz"},
{"org":"Skippad"},
{"org":"Kaymbo"},
{"org":"Yambee"},
{"org":"Ooba"},
{"org":"Midel"},
{"org":"Layo"},
{"org":"Rhynyx"},
{"org":"Ooba"},
{"org":"Thoughtbeat"},
{"org":"Fivebridge"},
{"org":"Eare"},
{"org":"Dabtype"},
{"org":"Dynabox"},
{"org":"Skibox"},
{"org":"Pixoboo"},
{"org":"Quamba"},
{"org":"Edgetag"},
{"org":"Lazz"},
{"org":"Flipopia"},
{"org":"Einti"},
{"org":"Skinder"},
{"org":"Eayo"},
{"org":"Tambee"},
{"org":"Devify"},
{"org":"Skimia"},
{"org":"Zoonoodle"},
{"org":"Tagtune"},
{"org":"Voonix"},
{"org":"Tagopia"},
{"org":"Avamm"},
{"org":"Cogilith"},
{"org":"Skibox"},
{"org":"Jayo"},
{"org":"Livetube"},
{"org":"Chatterbridge"},
{"org":"Vinder"},
{"org":"Fivespan"},
{"org":"Geba"},
{"org":"Rhyzio"},
{"org":"Bubblebox"},
{"org":"Tagpad"},
{"org":"Trudoo"},
{"org":"Kare"},
{"org":"Leenti"},
{"org":"Devpoint"},
{"org":"Kwinu"},
{"org":"Linkbridge"},
{"org":"Eamia"},
{"org":"Mybuzz"},
{"org":"Zazio"},
{"org":"Mydeo"},
{"org":"Zooxo"},
{"org":"Kamba"},
{"org":"Avaveo"},
{"org":"Blogtag"},
{"org":"Blogspan"},
{"org":"Skidoo"},
{"org":"Demimbu"},
{"org":"Flashdog"},
{"org":"Browsebug"},
{"org":"Meeveo"},
{"org":"Dazzlesphere"},
{"org":"Rhyzio"},
{"org":"Eabox"},
{"org":"Realcube"},
{"org":"Skidoo"},
{"org":"Mymm"},
{"org":"Dabvine"},
{"org":"Demimbu"},
{"org":"Kazu"},
{"org":"Wikibox"},
{"org":"Miboo"},
{"org":"Gigashots"},
{"org":"Youspan"},
{"org":"Flashpoint"},
{"org":"Quamba"},
{"org":"Jaxbean"},
{"org":"Fanoodle"},
{"org":"Topdrive"},
{"org":"Youbridge"},
{"org":"Jabbertype"},
{"org":"Quinu"},
{"org":"Voonte"},
{"org":"Quamba"},
{"org":"Meetz"},
{"org":"Feednation"},
{"org":"Janyx"},
{"org":"Rooxo"},
{"org":"Topicblab"},
{"org":"Trilia"},
{"org":"Twinder"},
{"org":"Ooba"},
{"org":"Devpoint"},
{"org":"Cogilith"},
{"org":"Miboo"},
{"org":"Fivechat"},
{"org":"Yotz"},
{"org":"Aimbo"},
{"org":"Edgeblab"},
{"org":"Janyx"},
{"org":"Quinu"},
{"org":"Jabbersphere"},
{"org":"Yozio"},
{"org":"Twitterbridge"},
{"org":"Blognation"},
{"org":"Muxo"},
{"org":"Thoughtblab"},
{"org":"Thoughtbeat"},
{"org":"Flashdog"},
{"org":"Tagchat"},
{"org":"Quatz"},
{"org":"Ailane"},
{"org":"Blogtags"},
{"org":"Riffpedia"},
{"org":"Brightdog"},
{"org":"Blogpad"},
{"org":"Jabberbean"},
{"org":"Oyoyo"},
{"org":"Yakijo"},
{"org":"Blogspan"},
{"org":"Riffpath"},
{"org":"Meevee"},
{"org":"Blognation"},
{"org":"Edgewire"},
{"org":"Zoombox"},
{"org":"Zava"},
{"org":"Thoughtmix"},
{"org":"Realcube"},
{"org":"Jabberbean"},
{"org":"Dabtype"},
{"org":"Oyonder"},
{"org":"Skajo"},
{"org":"Divavu"},
{"org":"BlogXS"},
{"org":"Feedbug"},
{"org":"Pixope"},
{"org":"Tagchat"},
{"org":"Leexo"},
{"org":"Linktype"},
{"org":"Tagtune"},
{"org":"Dabtype"},
{"org":"Kwilith"},
{"org":"Flashpoint"},
{"org":"Meemm"},
{"org":"InnoZ"},
{"org":"Eare"},
{"org":"Eimbee"},
{"org":"Demimbu"},
{"org":"Riffwire"},
{"org":"Eimbee"},
{"org":"Shuffletag"},
{"org":"Dabfeed"},
{"org":"Kaymbo"},
{"org":"Photospace"},
{"org":"Youspan"},
{"org":"Twitterlist"},
{"org":"Jayo"},
{"org":"Kaymbo"},
{"org":"Edgewire"},
{"org":"Kamba"},
{"org":"Youspan"},
{"org":"Bubblebox"},
{"org":"Babbleopia"},
{"org":"Tambee"},
{"org":"Rhyloo"},
{"org":"Demizz"},
{"org":"Flashset"},
{"org":"Zoomlounge"},
{"org":"Trunyx"},
{"org":"Muxo"},
{"org":"Lajo"},
{"org":"Kazio"},
{"org":"Skiba"},
{"org":"Youspan"},
{"org":"Skidoo"},
{"org":"Zoozzy"},
{"org":"Thoughtsphere"},
{"org":"Meevee"},
{"org":"Flashpoint"},
{"org":"Vitz"},
{"org":"Buzzdog"},
{"org":"Centizu"},
{"org":"Omba"},
{"org":"Feednation"},
{"org":"Wordify"},
{"org":"Flipopia"},
{"org":"Thoughtblab"},
{"org":"Twimbo"},
{"org":"Pixope"},
{"org":"Yamia"},
{"org":"Quinu"},
{"org":"Youopia"},
{"org":"Rhybox"},
{"org":"Fivespan"},
{"org":"Edgewire"},
{"org":"Riffwire"},
{"org":"Quamba"},
{"org":"Realcube"},
{"org":"Realfire"},
{"org":"Camido"},
{"org":"Camimbo"},
{"org":"Skajo"},
{"org":"Jabbertype"},
{"org":"Photofeed"},
{"org":"Fivechat"},
{"org":"Aivee"},
{"org":"Twiyo"},
{"org":"Gabspot"},
{"org":"Zoonoodle"},
{"org":"Meemm"},
{"org":"Quimm"},
{"org":"Devpoint"},
{"org":"Tazz"},
{"org":"Jayo"},
{"org":"Gabvine"},
{"org":"Vinte"},
{"org":"Ainyx"},
{"org":"Rhynoodle"},
{"org":"Skyba"},
{"org":"Jabbertype"},
{"org":"Babblestorm"},
{"org":"Skimia"},
{"org":"Fivebridge"},
{"org":"Demizz"},
{"org":"Shuffletag"},
{"org":"Zazio"},
{"org":"Kimia"},
{"org":"Feedfish"},
{"org":"Voolith"},
{"org":"Minyx"},
{"org":"Flashset"},
{"org":"Flipopia"},
{"org":"Yabox"},
{"org":"Dynabox"},
{"org":"Jaloo"},
{"org":"Fanoodle"},
{"org":"Janyx"},
{"org":"Zoonoodle"},
{"org":"Mydo"},
{"org":"Realbuzz"},
{"org":"Edgewire"},
{"org":"Oloo"},
{"org":"Yotz"},
{"org":"Yodo"}]
orgs = list(set([org["org"] for org in orgs]))

existing_org_IDs = {}

orgs_existing_members = {org: [] for org in orgs}
orgs_available_members = {org: list(names) for org in orgs}

def name_to_ID(name, org):
    return f'{name}@{org}.com'

def master_flow():
    manage_users.clear_orgs()
    manage_users.clear_hashes()

    sign_up_org_flow()
    member_creates_chat_flow()
    member_sends_message_flow()

    for _ in range(int(input("Iterations:"))):
        val = random.randint(1,100)
        if val == 1:
            sign_up_org_flow()
        elif val <= 5:
            sign_up_and_join_flow()
        elif val <= 30:
            copy_member_flow()
        elif val <= 50:
            member_creates_group_flow()
        elif val <= 75:
            member_creates_chat_flow()
        else:
            member_sends_message_flow()


def sign_up_org_flow():
    """
    Member Constructor - Create a new member with random name and email

    Sign Up -> Sign Up Org w/ first member ^

    Sign In -> Sign In New V2 (That member)

    Complete Sign Up and Join Existing Organisation flow for this organisation
    """

    count_calls[0]+=1

    org = orgs.pop()
    name = orgs_available_members[org].pop()
    orgs_existing_members[org].append(name)
    email = name_to_ID(name, org)

    with open("/Users/adam.gottlieb/PycharmProjects/Software_Mini_Major_Project/user/log.txt", "a") as f:
        print(name, 'signs up', org, file=f)

    member = Member(name, email)

    sign_up.sign_up_org(org, member)

    verified, org_ID, setup = sign_in.find_user(email)
    existing_org_IDs[org_ID] = org
    member_private = sign_in.sign_in_new_v2(org_ID, email)

    sign_up_and_join_flow(org_ID = org_ID)


def sign_up_and_join_flow(org_ID = None):
    """Member Constructor - Create a new member with random name and email

Create Random 8 character code = CODE and hash w/ SHA256 = HASH

Validate User -> Upload Verification Hash

Sign In -> Sign In Existing V2 (ANY existing member of that organisation)

Validate User -> Verify User (That existing member verifies new member with CODE)

Sign In -> Sign In Existing V2 (The NEW member)

Complete Member Creates Group in their Organisation flow for this member """

    count_calls[1]+=1
    if org_ID is None:
        org_ID = random.choice(list(existing_org_IDs.keys()))

    org = existing_org_IDs[org_ID]

    new_name = orgs_available_members[org].pop()
    new_email = f'{new_name}@{org}.com'

    with open("/Users/adam.gottlieb/PycharmProjects/Software_Mini_Major_Project/user/log.txt", "a") as f:
        print(new_name, 'joins', org, file=f)

    new_member = Member(new_name, new_email)

    code = "".join([random.choice(string.ascii_uppercase + string.digits) for _ in range(8)])

    hash_object = SHA256.new()
    hash_object.update(code.encode())
    hash = hash_object.hexdigest()

    validate_user.upload_verification_hash(new_name, new_email, hash)

    existing_member = random.choice(orgs_existing_members[org])

    existing_member_info = sign_in.sign_in_existing_v2(org_ID, f'{existing_member}@{org}.com')

    validate_user.verify_user(org_ID, existing_member_info.email, new_email, code)

    orgs_existing_members[org].append(new_name)

    new_member_info = sign_in.sign_in_new_v2(org_ID, new_email)

    member_creates_group_flow(new_member.email)
    member_creates_group_flow(existing_member_info.email)

def copy_member_flow():
    """Data Structures -> Member -> Member Constructor - Create a new member with random name and email

    Add them to a random organisation

    Sign In -> Sign In Existing V2 (ANY existing member of that organisation)

    Manage Users -> Complete User (using parameters from the existing member)

    Save AES Key as file"""

    count_calls[1]+=1

    org_ID = random.choice(list(existing_org_IDs.keys()))

    org = existing_org_IDs[org_ID]

    new_name = orgs_available_members[org].pop()
    new_email = f'{new_name}@{org}.com'

    with open("/Users/adam.gottlieb/PycharmProjects/Software_Mini_Major_Project/user/log.txt", "a") as f:
        print(new_name, 'is copied to', org, file=f)

    new_member = Member(new_name, new_email)

    manage_users.add_member(org_ID, new_member)

    existing_member = random.choice(orgs_existing_members[org])

    existing_member_info = sign_in.sign_in_existing_v2(org_ID, f'{existing_member}@{org}.com')

    rsa_pk = communicate.get_rsa_pks(org_ID, [existing_member_info.email])[existing_member_info.email]

    manage_users.complete_user(org_ID, new_email, rsa_pk, existing_member_info.rsa_sk_bundle)

    orgs_existing_members[org].append(new_name)

    with open(f"/Users/adam.gottlieb/PycharmProjects/Software_Mini_Major_Project/user/user_data/{new_email}_aes.bin", 'xb') as aes_file:
        aes_file.write(existing_member_info.aes)

    member_creates_group_flow(new_email)


def member_creates_group_flow(member_email = None):
    """Sign In -> Find User (The Member)

Sign In -> Sign In Existing V2 (The Member)

Data Structures -> Member Private -> Process Inbox

Chat Functionality V2 -> Create Group (Use random subset of members as participants)

Data Structures -> Member Private -> Add Group"""

    if member_email is None:
        org_ID = random.choice(list(existing_org_IDs.keys()))
        org = existing_org_IDs[org_ID]
        member_name = random.choice(orgs_existing_members[org])
        member_email = f'{member_name}@{org}.com'

    count_calls[2]+=1


    verified, org_ID, setup = sign_in.find_user(member_email)

    org = existing_org_IDs[org_ID]

    participant_IDs = [name_to_ID(member, org) for member in orgs_existing_members[org] if random.random() < 0.2]

    with open("/Users/adam.gottlieb/PycharmProjects/Software_Mini_Major_Project/user/log.txt", "a") as f:
        print(member_email, 'creates group in', org, 'with members', ", ".join(participant_IDs), file=f)

    member_info = sign_in.sign_in_existing_v2(org_ID, member_email)

    if member_info.ID not in participant_IDs: participant_IDs.append(member_info.ID)

    group = chat_functionality_v2.create_group(
        member_info.ID, org_ID, f'Group{random.randint(0,10**6)}', participant_IDs, member_info.rsa_sk)

    member_info.groups[group.ID] = group

    member_info.process_inbox()

def member_creates_chat_flow():
    """Sign In -> Find User (The Member)

Sign In -> Sign In Existing V2 (The Member)

Data Structures -> Member Private -> Process Inbox

Chat Functionality V2 -> Create Chat (Any of their groups at random)

Data Structures -> Member Private -> Update Group

Data Structures -> Member Private -> Process Inbox """

    count_calls[3] += 1

    org_ID = random.choice(list(existing_org_IDs.keys()))
    org = existing_org_IDs[org_ID]
    member_name = random.choice(orgs_existing_members[org])
    member_email = f'{member_name}@{org}.com'

    with open("/Users/adam.gottlieb/PycharmProjects/Software_Mini_Major_Project/user/log.txt", "a") as f:
        print(member_name, 'creates chat in', org, file=f)


    verified, org_ID, setup = sign_in.find_user(member_email)

    member_info = sign_in.sign_in_existing_v2(org_ID, member_email)

    org = existing_org_IDs[org_ID]

    group_ID = random.choice(list(member_info.groups.keys()))
    group = member_info.groups[group_ID]

    chat = chat_functionality_v2.create_chat(member_info.ID, org_ID, group, f'{group.name}, Chat{random.randint(0,10**6)}',member_info.rsa_sk)

    group.add_chats([chat])

    member_info.groups[group.ID] = group

    member_info.process_inbox()

def member_sends_message_flow():
    """Sign In -> Find User (The Member)

Sign In -> Sign In Existing V2 (The Member)

Data Structures -> Member Private -> Process Inbox

Send -> Send Message

Data Structures -> Member Private -> Process Inbox """

    count_calls[4] += 1

    org_ID = random.choice(list(existing_org_IDs.keys()))
    org = existing_org_IDs[org_ID]
    member_name = random.choice(orgs_existing_members[org])
    member_email = f'{member_name}@{org}.com'

    with open("/Users/adam.gottlieb/PycharmProjects/Software_Mini_Major_Project/user/log.txt", "a") as f:
        print(member_name, 'sends message in', org, file=f)


    verified, org_ID, setup = sign_in.find_user(member_email)

    member_info = sign_in.sign_in_existing_v2(org_ID, member_email)

    group_ID = random.choice(list(member_info.groups.keys()))
    group = member_info.groups[group_ID]

    chat = random.choice(group.chats)

    message_ID = auxiliary.get_new_random_ID([])
    recipient_IDs = [ID for ID in group.participant_IDs if ID != member_info.ID]

    message = Message(message_ID, group.ID, chat.ID, time.time(), member_info.email, None,
                         {'text': group.name+chat.name+' + Message'+str(random.randint(0,10**6))}, 'message')

    member_info.groups[group.ID].get_chat(chat.ID).messages.append(message)

    send.send_message(org_ID, recipient_IDs, member_info.rsa_sk, message)

    member_info.process_inbox()


if __name__ == '__main__':
    try:
        master_flow()

    except Exception as e:
        with open("error.txt", "w") as f:
            f.write(str(e))


        with open("count_calls.txt", "w") as f:
            json.dump(count_calls, f)

        import integrated_testing_check

        raise

    except KeyboardInterrupt:

        pass

    with open("count_calls.txt", "w") as f:
        json.dump(count_calls, f)

    import integrated_testing_check
















